apiVersion: v1
kind: Service
metadata:
  name: echo-pods-argo
spec:
#   type: NodePort
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: echo-pods-argo
